/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package nic.vahan.services.clients.dobj;

import java.math.BigDecimal;
import java.util.Date;

/**
 * generated by hbm2java
 */
public class VtDocuments implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    private Integer id;
    private String appl_no;
    private String regn_no;
    private String doc_catg_id;
    private Integer doc_id;
    private BigDecimal doc_code;
    private String doc_unique_no;
    private Date doc_uploaded_dt;
    private String doc_url;
    private String state_cd;
    private Integer off_cd;
    private boolean isuploaded;
    private boolean doc_verified;
    private boolean doc_approved;
    private boolean doc_recieved;
    private Date doc_verified_dt;
    private Date doc_approve_dt;
    private Date doc_recieve_dt;
    private boolean temp_doc_approved;
    private Date temp_doc_approve_dt;
    private String bio_id;
    private String doc_object_id;
    private String folder_name;
    private String file_name;
    private byte[] fileToUpload = null;
    private long fileSize = 0l;
    private String mimeType = null;
    private String message;
    private String old_doc_url;

    public VtDocuments() {
    }

    public VtDocuments(Integer inId,
            String inAppl_no,
            String inRegn_no,
            String inDoc_catg_id,
            Integer inDoc_id,
            String inDoc_unique_no,
            Date inDoc_uploaded_dt,
            String inDoc_url,
            String inState_cd,
            Integer inOff_cd,
            boolean inIsuploaded,
            boolean inDoc_verified,
            boolean inDoc_approved,
            boolean inDoc_recieved,
            Date inDoc_verified_dt,
            Date inDoc_approve_dt,
            Date inDoc_recieve_dt,
            boolean inTemp_doc_approved,
            Date inTemp_doc_approve_dt,
            String inBio_id) {
        id = inId;
        appl_no = inAppl_no;
        regn_no = inRegn_no;
        doc_catg_id = inDoc_catg_id;
        doc_id = inDoc_id;
        doc_unique_no = inDoc_unique_no;
        doc_uploaded_dt = inDoc_uploaded_dt;
        doc_url = inDoc_url;
        state_cd = inState_cd;
        off_cd = inOff_cd;
        isuploaded = inIsuploaded;
        doc_verified = inDoc_verified;
        doc_approved = inDoc_approved;
        doc_recieved = inDoc_recieved;
        doc_verified_dt = inDoc_verified_dt;
        doc_approve_dt = inDoc_approve_dt;
        doc_recieve_dt = inDoc_recieve_dt;
        temp_doc_approved = inTemp_doc_approved;
        temp_doc_approve_dt = inTemp_doc_approve_dt;
        bio_id = inBio_id;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer inId) {
        id = inId;
    }

    public String getAppl_no() {
        return appl_no;
    }

    public void setAppl_no(String inAppl_no) {
        appl_no = inAppl_no;
    }

    public String getRegn_no() {
        return regn_no;
    }

    public void setRegn_no(String inRegn_no) {
        regn_no = inRegn_no;
    }

    public String getDoc_catg_id() {
        return doc_catg_id;
    }

    public void setDoc_catg_id(String inDoc_catg_id) {
        doc_catg_id = inDoc_catg_id;
    }

    public Integer getDoc_id() {
        return doc_id;
    }

    public void setDoc_id(Integer inDoc_id) {
        doc_id = inDoc_id;
    }

    public BigDecimal getDoc_code() {
        return doc_code;
    }

    public void setDoc_code(BigDecimal doc_code) {
        this.doc_code = doc_code;
        if (null != this.doc_code) {
            setDoc_id(this.doc_code.intValue());
        }
    }

    public String getDoc_unique_no() {
        return doc_unique_no;
    }

    public void setDoc_unique_no(String inDoc_unique_no) {
        doc_unique_no = inDoc_unique_no;
    }

    public Date getDoc_uploaded_dt() {
        return doc_uploaded_dt;
    }

    public void setDoc_uploaded_dt(Date inDoc_uploaded_dt) {
        doc_uploaded_dt = inDoc_uploaded_dt;
    }

    public String getDoc_url() {
        return doc_url;
    }

    public void setDoc_url(String inDoc_url) {
        doc_url = inDoc_url;
    }

    public String getState_cd() {
        return state_cd;
    }

    public void setState_cd(String inState_cd) {
        state_cd = inState_cd;
    }

    public Integer getOff_cd() {
        return off_cd;
    }

    public void setOff_cd(Integer inOff_cd) {
        off_cd = inOff_cd;
    }

    public boolean isIsuploaded() {
        return isuploaded;
    }

    public void setIsuploaded(boolean inIsuploaded) {
        isuploaded = inIsuploaded;
    }

    public boolean isDoc_verified() {
        return doc_verified;
    }

    public void setDoc_verified(boolean inDoc_verified) {
        doc_verified = inDoc_verified;
    }

    public boolean isDoc_approved() {
        return doc_approved;
    }

    public void setDoc_approved(boolean inDoc_approved) {
        doc_approved = inDoc_approved;
    }

    public boolean isDoc_recieved() {
        return doc_recieved;
    }

    public void setDoc_recieved(boolean inDoc_recieved) {
        doc_recieved = inDoc_recieved;
    }

    public Date getDoc_verified_dt() {
        return doc_verified_dt;
    }

    public void setDoc_verified_dt(Date inDoc_verified_dt) {
        doc_verified_dt = inDoc_verified_dt;
    }

    public Date getDoc_approve_dt() {
        return doc_approve_dt;
    }

    public void setDoc_approve_dt(Date inDoc_approve_dt) {
        doc_approve_dt = inDoc_approve_dt;
    }

    public Date getDoc_recieve_dt() {
        return doc_recieve_dt;
    }

    public void setDoc_recieve_dt(Date inDoc_recieve_dt) {
        doc_recieve_dt = inDoc_recieve_dt;
    }

    public boolean isTemp_doc_approved() {
        return temp_doc_approved;
    }

    public void setTemp_doc_approved(boolean inTemp_doc_approved) {
        temp_doc_approved = inTemp_doc_approved;
    }

    public Date getTemp_doc_approve_dt() {
        return temp_doc_approve_dt;
    }

    public void setTemp_doc_approve_dt(Date inTemp_doc_approve_dt) {
        temp_doc_approve_dt = inTemp_doc_approve_dt;
    }

    public String getBio_id() {
        return bio_id;
    }

    public void setBio_id(String inBio_id) {
        bio_id = inBio_id;
    }

    public String getDoc_object_id() {
        return doc_object_id;
    }

    public void setDoc_object_id(String inDoc_object_id) {
        doc_object_id = inDoc_object_id;
    }

    public String getFolder_name() {
        return folder_name;
    }

    public void setFolder_name(String inFolder_name) {
        folder_name = inFolder_name;
    }

    public String getFile_name() {
        return file_name;
    }

    public void setFile_name(String inFile_name) {
        file_name = inFile_name;
    }

    public byte[] getFileToUpload() {
        return fileToUpload;
    }

    public void setFileToUpload(byte[] fileToUpload) {
        this.fileToUpload = fileToUpload;
    }

    public long getFileSize() {
        return fileSize;
    }

    public void setFileSize(long fileSize) {
        this.fileSize = fileSize;
    }

    public String getMimeType() {
        return mimeType;
    }

    public void setMimeType(String inMimeType) {
        mimeType = inMimeType;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public String getOld_doc_url() {
        return old_doc_url;
    }

    public void setOld_doc_url(String inOld_doc_url) {
        old_doc_url = inOld_doc_url;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((appl_no == null) ? 0 : appl_no.hashCode());
        result = prime * result + ((doc_catg_id == null) ? 0 : doc_catg_id.hashCode());
        result = prime * result + ((doc_id == null) ? 0 : doc_id.hashCode());
        return result;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        VtDocuments other = (VtDocuments) obj;
        if (appl_no == null) {
            if (other.appl_no != null) {
                return false;
            }
        } else if (!appl_no.equals(other.appl_no)) {
            return false;
        }
        if (doc_catg_id == null) {
            if (other.doc_catg_id != null) {
                return false;
            }
        } else if (!doc_catg_id.equals(other.doc_catg_id)) {
            return false;
        }
        if (doc_id == null) {
            if (other.doc_id != null) {
                return false;
            }
        } else if (!doc_id.equals(other.doc_id)) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "VtDocuments [id=" + id + ", appl_no=" + appl_no + ", regn_no=" + regn_no + ", doc_catg_id="
                + doc_catg_id + ", doc_id=" + doc_id + ", doc_code=" + doc_code + ", doc_unique_no=" + doc_unique_no
                + ", doc_uploaded_dt=" + doc_uploaded_dt + ", doc_url=" + doc_url + ", state_cd=" + state_cd
                + ", off_cd=" + off_cd + ", isuploaded=" + isuploaded + ", doc_verified=" + doc_verified
                + ", doc_approved=" + doc_approved + ", doc_recieved=" + doc_recieved + ", doc_verified_dt="
                + doc_verified_dt + ", doc_approve_dt=" + doc_approve_dt + ", doc_recieve_dt=" + doc_recieve_dt
                + ", temp_doc_approved=" + temp_doc_approved + ", temp_doc_approve_dt=" + temp_doc_approve_dt
                + ", bio_id=" + bio_id + ", doc_object_id=" + doc_object_id + ", folder_name=" + folder_name
                + ", file_name=" + file_name + ",  fileSize=" + fileSize + ", mimeType=" + mimeType + ", message="
                + message + ", old_doc_url=" + old_doc_url + "]";
    }
}
