package nic.vahan.db;
///////////////////////////////////////////////////////////////////////////////
// CLASS            : TableConstants
// PURPOSE          : Defines constants specific to database table structure.
// NOTES            : None
// LAST MODIFIED    :

//////////////////////////////////////////////////////////////////////////////
// Copyright 2003 National Informatics Centre, NIC. http://www.nic.in
// All Rights Reserved.
//////////////////////////////////////////////////////////////////////////////
public interface TableConstants {

    /**
     * Fee code for issue of issue of NOC
     */
    int VM_TRANSACTION_MAST_NOC = 9;
    int USER_ROLE_CASHIER = 9;
    int VM_TRANSACTION_MAST_NOC_CANCEL = 91;
    int VM_PMT_SURCHARG_FEE = 92;
    String VT_NOC_ISSUE_STATUS = "N";
    String VT_RC_SURRENDER_STATUS = "S";
    String VT_RC_SUSPEND_STATUS = "D";
    String VT_RC_RELEASE_STATUS = "Y";
    String VT_RC_ACTIVE_STATUS = "A";
    String VT_RC_CANCEL_STATUS = "C";
    String VT_DE_REGISTRATION = "X";
    String VT_SCRAP_VEHICLE_STATUS = "T";
    String VM_PMT_TYPE_IN_TAX_CODE = "<25>";
    String VM_PMT_CATG_IN_TAX_CODE = "<28>";
    int VM_TRANSACTION_MAST_MISC = 48;
    int VM_TRANSACTION_MAST_DIFF_FEE = 85;
    int VM_TRANSACTION_MAST_DIFF_TAX = 86;
    /**
     * Fee code for issue of fitness certificate
     */
    int VM_TRANSACTION_MAST_FIT_CERT = 2;
    int VM_VEHICLE_INSPECTION_FEE = 202;
    /**
     * Fee code for New vehicle
     */
    int VM_TRANSACTION_MAST_NEW_VEHICLE = 1;
    int VM_TRANSACTION_MAST_ADDL_TO_VEHICLE = 96;
    int VM_TRANSACTION_MAST_DEALER_NEW_VEHICLE = 123;
    int VM_TRANSACTION_MAST_DEALER_TEMP_VEHICLE = 124;
    int TM_ROLE_DEALER_NEW_APPL = 12304;
    int TM_ROLE_DEALER_VERIFICATION = 12305;
    int TM_ROLE_DEALER_APPROVAL = 12306;
    int TM_ROLE_DEALER_NEW_REGN_FEE = 12301;
    int TM_ROLE_DEALER_CART_PAYMENT = 12302;
    int TM_ROLE_DEALER_APPLICATION_DISPOSE = 12310;
    int TM_NEW_RC_VERIFICATION = 10005;
    int TM_NEW_RC_FITNESS_INSPECTION = 10001;
    int TM_NEW_RC_FITNESS_INSPECTION_APPROVAL = 10011;
    int VM_TRANSACTION_MAST_NEW_VEHICLE_FITNESS = 122;
    int TM_NEW_VEHICLE_FITNESS_INSPECTION = 12204;
    int TM_NEW_VEHICLE_FITNESS_INSPECTION_VERIFICATION = 12205;
    int TM_NEW_VEHICLE_FITNESS_INSPECTION_APPROVAL = 12206;
    int TM_NEW_RC_APPROVAL = 10006;
    int TM_NEW_RC_ADMIN_APPROVE = 10106;
    int TM_OWNER_ADMIN = 66660;
    int TM_ROLE_DEALER_TEMP_APPL = 12404;
    int TM_ROLE_DEALER_TEMP_VERIFICATION = 12405;
    int TM_ROLE_DEALER_TEMP_REGN_FEE = 12401;
    int TM_ROLE_DEALER_TEMP_CART_PAYMENT = 12402;
    int TM_ROLE_DEALER_TEMP_APPROVAL = 12406;
    int TM_ROLE_DEALER_PRINT_TMP_RC = 12407;
    int VM_ROLE_RC_CANCELLATION_INSPECTION = 61001;
    //int TM_ROLE_DEALER_PRINT_TMP_RC_AT_RTO = 12408;
    int TM_TMP_RC_VERIFICATION = 18005;
    int TM_TMP_RC_APPROVAL = 18006;
    int TM_TMP_ROLE_ENTRY = 18004;
    int TM_TMP_RC_FITNESS_INSPECTION = 18001;
    String User_Dealer = "B";
    String REGN_TYPECODE = "N";
    int TM_ROLE_BALANCE_FEE_TAX_COLLECTION = 99912;
    int TM_ROLE_AUDIT = 88814;
    /**
     * Fee code for Renewal of registration
     */
    int VM_TRANSACTION_MAST_REN_REG = 15;
    /**
     * Fee code for Reassignment of registration number
     */
    int VM_TRANSACTION_MAST_REASSIGN_REGN_NO = 17;
    /**
     * Fee code for duplicate RC
     */
    int VM_TRANSACTION_MAST_DUP_RC = 3;
    int VM_TRANSACTION_MAST_TO = 5;
    /**
     * Fee code for addition of hypothecation
     */
    int VM_TRANSACTION_MAST_ADD_HYPO = 6;
    /**
     * Fee code for removal of hypothecation
     */
    int VM_TRANSACTION_MAST_REM_HYPO = 7;
    /**
     * Fee code for Fees with All transactions
     */
    int VM_TRANSACTION_MAST_ALL = 100;
    /**
     * Fee code for continution of hypothecation
     */
    int VM_TRANSACTION_MAST_HPC = 8;
    /**
     * Fee code for change of address
     */
    int VM_TRANSACTION_MAST_CHG_ADD = 4;
    /**
     * User Messaging
     */
    int VM_USER_MESSAGING = 451;
    /**
     * Fee code for Vehicle Conversion
     */
    int VM_TRANSACTION_MAST_VEH_CONVERSION = 11;
    int VM_TRANSACTION_MAST_VEH_CONVERSION_ENTRY = 11004;
    /**
     * Fee code for vehicle alteration
     */
    int VM_TRANSACTION_MAST_VEH_ALTER = 16;
    int VM_TRANSACTION_MAST_VEH_ALTER_ENTRY = 16004;
    int VM_TRANSACTION_MAST_VEH_ALTER_VERIFY = 16005;
    int VM_TRANSACTION_MAST_VEH_ALTER_APPROVE = 16006;
    int VM_TRANSACTION_MAST_RC_PARTICULARS_FOR_OFFICE_PURPOSE = 73;
    int VM_TRANSACTION_MAST_RC_PARTICULARS = 13;
    int VM_TRANSACTION_MAST_RC_PARTICULARS_OWNER = 174;
    int VM_TRANSACTION_MAST_RC_PARTICULARS_COMPANY = 173;
    /**
     * Trade certificate module constants
     */
    int VM_TRANSACTION_TRADE_CERT_NEW = 21;
    int VM_TRANSACTION_TRADE_CERT_DUP = 22;
    int VM_TRANSACTION_TRADE_CERT_ONLINE_APPLICATION = 51;
    int TM_ROLE_TRADE_CERT_APPL_ENTRY = 21004;
    int TM_ROLE_TRADE_CERT_DEALER_APPL_ENTRY = 21104;
    int TM_ROLE_TRADE_CERT_DEALER_APPL_INSPECT = 21114;
    int TM_ROLE_TRADE_CERT_DEALER_APPL_VERIFY = 21115;
    int TM_ROLE_TRADE_CERT_DEALER_APPL_APPROVE = 21116;
    int TM_ROLE_TRADE_CERT_FEE = 21003;
    int TM_ROLE_TRADE_CERT_VERIFICATION = 21005;
    int TM_ROLE_TRADE_CERT_APPROVE = 21006;
    int TM_ROLE_TRADE_CERT_PRINT = 21007;
    int TM_ROLE_TRADE_CERT_APPL_ENTRY_DUP = 22004;
    int TM_ROLE_TRADE_CERT_FEE_DUP = 22003;
    int TM_ROLE_TRADE_CERT_VERIFICATION_DUP = 22005;
    int TM_ROLE_TRADE_CERT_APPROVE_DUP = 22006;
    int TM_ROLE_TRADE_CERT_PRINT_DUP = 22007;
    int TM_ROLE_TRADE_CERT_ONLINE_APPL_RECEIVE = 51004;
    int TM_ROLE_TRADE_CERT_ONLINE_APPL_VERIFICATION = 51005;
    int TM_ROLE_TRADE_CERT_ONLINE_APPL_APPROVE = 51006;
    String TRADE_CERT_ENDORSEMENT_CONSTANT_VAL = "E";
    String TRADE_CERT_DUPLICATE_CONSTANT_VAL = "D";
    int VM_CANCEL_TRADE_CERT = 67;
    int VM_CANCEL_TRADE_CERT_ENTRY = 67004;
    int VM_CANCEL_TRADE_CERT_VERIFY = 67005;
    int VM_CANCEL_TRADE_CERT_APPROVE = 67006;
    String TRADE_CERT_PENDING_FOR_PAYMENT_VAL = "R";
    String TRADE_CERT_STRING_SPLIT_CONSTANT = "#";
    /**
     * temp registration
     */
    int VM_TRANSACTION_MAST_TEMP_REG = 18;
    int VM_TRANSACTION_MAST_TEMP_TAX = 20;
    int VM_TRANSACTION_MAST_DUP_FC = 14;
    /**
     * Fresh Rc In The Name Of Financer
     */
    int VM_TRANSACTION_MAST_FRESH_RC = 12;
    /*purpose code for Choice no*/
    int VM_TRANSACTION_MAST_CHOICE_NO = 95;
    int VM_TRANSACTION_MAST_USER_CHARGES = 99;
    /**
     * TEMP REG flag for VT_VEH_CATG
     */
    String VT_VEH_CATG_TEMP_REG = "T";
    /**
     * Vehicle Registration type New
     */
    int VM_TRANSACTION_MAST_SMART_CARD_FEE = 80;
    /**
     * Fee code for Duplicate to Tax Card
     */
    int VM_DUPLICATE_TO_TAX_CARD = 72;
    String VM_REGN_TYPE_NEW = "N";
    String VM_REGN_TYPE_TEMPORARY = "T";
    String VM_REGN_TYPE_EXARMY = "A";
    String VM_REGN_TYPE_OTHER_STATE_VEHICLE = "O";
    String VM_REGN_TYPE_OTHER_DISTRICT_VEHICLE = "R";
    String VM_REGN_TYPE_SCRAPPED = "S";
    String VM_REGN_TYPE_IMPORTED_YES = "Y";
    String VM_REGN_TYPE_CD = "D";
    int VM_FUEL_CNG_TYPE = 3;
    int VM_FUEL_TYPE_LPG = 8;
    int VM_FUEL_TYPE_PETROL_LPG = 5;
    int VM_FUEL_TYPE_PETROL_CNG = 6;
    int VM_FUEL_TYPE_ELECTRIC = 4;
    int VM_FUEL_TYPE_DIESEL = 2;
    int VM_FUEL_TYPE_DIESEL_HYPBRID = 12;
    int VM_VEHTYPE_TRANSPORT = 1;
    int VM_VEHTYPE_NON_TRANSPORT = 2;
    String VM_VEHTYPE_TRANSPORT_DESCR = "Transport";
    String VM_VEHTYPE_NON_TRANSPORT_DESCR = "Non-Transport";
    int VM_VEHTYPE_ALL = 3;
    String VIEW_OWNER = "vv_owner";
    String TM_PAYMENT_MODE_CASH = "C";
    int OWNER_CODE_INDIVIDUAL = 1;
    int OWNER_CODE_FIRM = 2;
    int OWNER_CATG_OTHERS = 6;
    int OWNER_CODE_JOINT_STOCK = 3;
    int OWNER_CODE_MULTIPLE_OWNER = 7;
    String NATIONAL_PERMIT = "106";
    String GOODS_PERMIT = "105";
    String AITP = "103";
    String CC_PERMIT = "102";
    String PSV_PERMIT = "104";
    int CONTRACT_CARRIAGE_PERMIT = 102;
    int STAGE_CARRIAGE_PERMIT = 101;
    int FRESH_RC_TO_FINANCIER_APPROVAL = 12006;
    /**
     * *
     * Roles
     *
     */
    //added By Nitin Kumar 12-05-2015
    int VM_MAST_VEHICLE_SCRAPE = 349;
    int VM_MAST_RC_SURRENDER = 65;
    int VM_MAST_RC_RELEASE = 66;
    int VM_MAST_RC_CANCELLATION = 61;
    int VM_ROLE_RC_SURRENDER_ENTRY = 65004;
    int VM_ROLE_RC_SURRENDER_VERIFICATION = 65005;
    int VM_ROLE_RC_SURRENDER_APPROVAL = 65006;
    int VM_ROLE_RC_RELEASE_ENTRY = 66004;
    int VM_ROLE_RC_RELEASE_VERIFICATION = 66005;
    int VM_ROLE_RC_RELEASE_APPROVAL = 66006;
    int VM_ROLE_RC_CANCELLATION_ENTRY = 61004;
    int VM_ROLE_RC_CANCELLATION_VERIFICATION = 61005;
    int VM_ROLE_RC_CANCELLATION_APPROVAL = 61006;
    //added By Nitin Kumar 12-05-2015
    int VM_MAST_ENFORCEMENT = 111;
    int VM_MAST_ENFORCEMENT_DISPOSE = 112;
    int VM_MAST_ENFORCEMENT_RELEASE_DOC_VEHICLE = 113;
    int VM_MAST_ENFORCEMENT_FEE_TAX = 999;
    int VM_ROLE_ENFORCEMENT_ENTRY = 11104;
    int VM_ROLE_ENFORCEMENT_VERIFY = 11105;
    int VM_ROLE_ENFORCEMENT_APPROVE = 11106;
    int VM_ROLE_ENFORCEMENT_DISPOSE_ENTRY = 11204;
    int VM_ROLE_ENFORCEMENT_DISPOSE_VERIFY = 11205;
    int VM_ROLE_ENFORCEMENT_DISPOSE_APPROVE = 11206;
    int VM_ROLE_ENFORCE_DUP_AND_CHALLAN_CANCEL = 11704;
    int VM_ROLE_ENFORCE_HOLD_ACTIVE_CHALLAN = 11705;
    int VM_ROLE_ENFORCEMENT_RELEASE_DOC_VEHICLE_ENTRY = 11304;
    int VM_ROLE_ENFORCEMENT_RELEASE_DOC_VEHICLE_VERIFY = 11305;
    int VM_ROLE_ENFORCEMENT_RELEASE_DOC_VEHICLE_APPROVE = 11306;
    int VM_ROLE_ENFORCEMENT_SETTLMENT_ENTRY = 11404;
    int VM_ROLE_ENFORCEMENT_SETTLMENT_VERIFY = 11405;
    int VM_ROLE_ENFORCEMENT_SETTLMENT_APPROVE = 11406;
    int VM_ROLE_ENFORCEMENT_FEE_TAX = 99996;
    int VM_ROLE_ENFORCEMENT_CHALLAN_REFER_TO_COURT = 11504;
    int TM_ROLE_INSPECTION = 01;
    int TM_ROLE_RANDOM_MARK_GENERATION = 02;
    int TM_ROLE_RANDOM_MARK_ACTION_CD = 10002;
    int TM_ROLE_PRINT_RC = 10007;
    int TM_ROLE_PRINT_TMP_RC = 18007;
    int TM_ROLE_FANCY_NUMBER_FEE = 95001;
    int TM_ROLE_FANCY_NUMBER_ENTRY = 95004;
    int TM_ROLE_FANCY_NUMBER_VERIFY = 95005;
    int TM_ROLE_FANCY_NUMBER_APPROVE = 95006;
    int TM_ROLE_TAX_SLABS_ENTRY = 66661;
    int TM_ROLE_FEE_SLABS_ENTRY = 66662;
    int TM_ROLE_SCRUTINY_E_PAY = 03;
    int TM_ROLE_ENTRY = 04;
    int TM_ROLE_VERIFICATION = 05;
    int TM_ROLE_APPROVAL = 06;
    int TM_ROLE_PRINT = 07;
    int TM_ROLE_NEW_APPL = 88881;
    int TM_ROLE_REV_NEW_APPL = 81;
    int TM_ROLE_NEW_APPL_TEMP = 88882;
    int TM_ROLE_REV_NEW_APPL_TEMP = 82;
    int TM_ROLE_APPLICATION_INWARD = 88885;
    int TM_ROLE_TAX_CLEAR_ENTRY = 34501;
    int TM_ROLE_TAX_CLEAR_VERIFICATION = 34505;
    int TM_ROLE_TAX_CLEAR_APPROVAL = 34506;
    int TM_ROLE_TAX_CLEAR_APPROVAL_AS = 34508;
    int TM_ROLE_INSTALLMENT_BRKUP_ENTRY = 35501;
    int TM_ROLE_INSTALLMENT_BRKUP_VERIFICATION = 35505;
    int TM_ROLE_INSTALLMENT_BRKUP_APPROVAL = 35506;
    int FITNESS_CANCEL_ENTRY = 35204;
    int FITNESS_CANCEL_VERIFICATION = 35205;
    int FITNESS_CANCEL_APPROVAL = 35206;
    int TM_PURPOSE_FITNESS_CANCELLATION = 352;
    int TM_ROLE_SCRAPPED_VEHICLE_ENTRY = 34904;
    int TM_ROLE_SCRAPPED_VEHICLE_VERIFICATION = 34905;
    int TM_ROLE_SCRAPPED_VEHICLE_APPROVAL = 34906;
    String TM_ROLE_NUMBER_ALLOCATION = "11";
    String STATUS_CANCEL = "R";
    String STATUS_COMPLETE = "C";
    String STATUS_NOT_STARTED = "N";
    String STATUS_REVERT = "M";
    String STATUS_HOLD = "I";
    String STATUS_DISPATCH_PENDING = "I";
    String STATUS_APPROVED = "A";
    String BACKWARD = "B";
    String FORWARD = "F";
    String DISPOSE = "D";
    String FEECANCELSTATUS = "Z";
    String STATUS_PULLBACK = "P";
    String STATUS_NOT_RECOMMEND = "X";
    /**
     * Road tax code
     *
     */
    int PASSENGER_TAX = 54;
    int GOODS_TAX = 55;
    int TM_ROAD_TAX = 58;
    int TM_ADDN_ROAD_TAX = 59;
    int TM_AUDIO_FEE = 81;
    int TM_VIDEO_FEE = 82;
    int TM_ENVIRONMENT_TAX = 346;
    int TRADE_CERTIFICATE_TAX = 89;
    int TRADE_CERTIFICATE_SURCHARGE = 250;
    String TM_ROAD_TAX_DESC = "Road Tax";
    String TM_ADDN_ROAD_TAX_DESC = "Add Road tax";
    /*
     * Flags For Fancy Numbers
     */
    String FANCY_REJECTED = "R";
    String FANCY_ACCEPTED = "A";
    String FANCY_PAID = "P";
    int INITIAL_FLOW_WS_URL = 1;
    int NEXT_FLOW_WS_URL = 2;
    String RANDOM_NUMBER_STATUS_P = "P";
    String RANDOM_NUMBER_STATUS_A = "A";
    String RANDOM_NUMBER_STATUS_M = "M";
    String STATE_CD = "KL";
    int PY_AITP_SZ_CATG = 29;
    boolean isNextStageWebService = false;
    int VM_PMT_APPLICATION_PUR_CD = 25;
    int SCAN_FEE_PUR = 162;
    int SOCIETY_FEE_PUR = 163;
    int WELFARE_TAX = 68;
    int VM_PMT_FRESH_PUR_CD = 26;
    int VM_PMT_RENEWAL_PUR_CD = 27;
    int VM_PMT_TRANSFER_PUR_CD = 28;
    int VM_PMT_TRANSFER_DEATH_CASE_PUR_CD = 29;
    int VM_PMT_VARIATION_ENDORSEMENT_PUR_CD = 31;
    int VM_PMT_CA_PUR_CD = 32;
    int VM_PMT_CANCELATION_PUR_CD = 33;
    int VM_PMT_SUSPENSION_PUR_CD = 403;
    int VM_PMT_DUPLICATE_PUR_CD = 34;
    int VM_PMT_TEMP_PUR_CD = 35;
    int VM_PMT_RENEW_TEMP_PUR_CD = 53;
    int VM_PMT_SPECIAL_PUR_CD = 36;
    int VM_PMT_DIFFERENTIAL_SPECIAL_TAX = 102;
    int VM_PMT_HOME_AUTH_PERMIT_PUR_CD = 37;
    int VM_PMT_COUNTER_SIGNATURE_PUR_CD = 38;
    int VM_PMT_DUP_COUNTER_SIGNATURE_PUR_CD = 407;
    int VM_PMT_RENEW_COUNTER_SIGNATURE_PUR_CD = 408;
    int VM_PMT_PERMIT_PARTICULAR_PUR_CD = 409;
    int VM_PMT_PERMIT_PARTICULAR_PUR_CD_WITHOUT_FEE = 410;
    int VM_PMT_LEASE_PUR_CD = 401;
    int VM_PMT_LEASE_CANCEL_PUR_CD = 402;
    int VM_PMT_RENEWAL_HOME_AUTH_PERMIT_PUR_CD = 39;
    int VM_PMT_SURRENDER_PUR_CD = 41;
    int VM_PMT_RESTORE_PUR_CD = 42;
    int VM_PMT_REPLACE_VEH_PUR_CD = 43;
    int VM_PMT_TRANSFER_REPLACE_VEH_PUR_CD = 45;
    int VM_PMT_TRANSFER_REPLACE_OTHER_OFFICE_PUR_CD = 405;
    int VM_PMT_PERMANENT_SURRENDER_PUR_CD = 46;
    int VM_PMT_EXEMPTION_PUR_CD = 47;
    int VM_PMT_COMPOSIT_FEE_PUR_CD = 93;
    int VM_PMT_RE_ASSIGMENT_PUR_CD = 49;
    int VM_PMT_COUNTER_SIGNATURE_AUTH_PUR_CD = 412;
    int VM_PMT_SMART_CARD_FEE = 50;
    int VM_PARKING_FEE_PUR_CD = 90;
    int VM_FIT_EXEMPTION_PUR_CD = 351;
    int VM_PARK_EXEMPTION_PUR_CD = 353;
    int TM_ROLE_PMT_APPL = 88884;
    int TM_ROLE_PMT_APPL_FEE = 99995;
    int TM_ROLE_PMT_TEMP_FEE = 99998;
    int TM_ROLE_PMT_SPECIAL_FEE = 99979;
    int TM_ROLE_PMT_SCRUTINY = 26004;
    int TM_ROLE_PMT_VERIFICATION = 26005;
    int TM_ROLE_PMT_OFFER_VERIFICATION = 26008;
    int TM_ROLE_PMT_APPROVE = 26006;
    int TM_ROLE_PMT_RENWAL_SCRUTINY = 27004;
    int TM_ROLE_PMT_RENWAL_VERIFICATION = 27005;
    int TM_ROLE_PMT_RENWAL_APPROVE = 27006;
    int TM_ROLE_PMT_SURRENDER_TRANSFER_VERIFICATION = 28005;
    int TM_ROLE_PMT_SURRENDER_TRANSFER_APPROVE = 28006;
    int TM_ROLE_PMT_SURRENDER_TRANSFER_IN_DEATH_VERIFICATION = 29005;
    int TM_ROLE_PMT_SURRENDER_TRANSFER_IN_DEATH_APPROVE = 29006;
    int TM_ROLE_PMT_VARIATION_ENDORSEMENT_APPL = 31004;
    int TM_ROLE_PMT_VARIATION_ENDORSEMENT_VERIFICATION = 31005;
    int TM_ROLE_PMT_VARIATION_ENDORSEMENT_APPROVAL = 31006;
    int TM_ROLE_PMT_CA_VERIFICATION = 32005;
    int TM_ROLE_PMT_SUSPENSION_VERIFICATION = 40305;
    int TM_ROLE_PMT_CA_APPROVAL = 32006;
    int TM_ROLE_PMT_SUSPENSION_APPROVAL = 40306;
    int TM_ROLE_PMT_CANCEL_VERIFICATION = 33005;
    int TM_ROLE_PMT_CANCEL_APPROVAL = 33006;
    int TM_ROLE_PMT_COUNTER_SIGNATURE_AUTH_ENTRY = 41204;
    int TM_ROLE_PMT_COUNTER_SIGNATURE_AUTH_VERIFICATION = 41205;
    int TM_ROLE_PMT_COUNTER_SIGNATURE_AUTH_APPROVAL = 41206;
    int TM_ROLE_PMT_COUNTER_SIGNATURE_ENTRY = 38004;
    int TM_ROLE_PMT_COUNTER_SIGNATURE_VERIFICATION = 38005;
    int TM_ROLE_PMT_COUNTER_SIGNATURE_APPROVAL = 38006;
    int TM_ROLE_PMT_DUPCOUNTER_SIGNATURE_ENTRY = 40704;
    int TM_ROLE_PMT_DUPCOUNTER_SIGNATURE_VERIFICATION = 40705;
    int TM_ROLE_PMT_DUPCOUNTER_SIGNATURE_APPROVAL = 40706;
    int TM_ROLE_PMT_RENEW_COUNTER_SIGNATURE_VERIFICATION = 40805;
    int TM_ROLE_PMT_RENEW_COUNTER_SIGNATURE_APPROVAL = 40806;
    int TM_ROLE_PMT_LEASE_PERMIT_ENTRY = 40104;
    int TM_ROLE_PMT_LEASE_PERMIT_VERIFICATION = 40105;
    int TM_ROLE_PMT_LEASE_PERMIT_APPROVAL = 40106;
    int TM_ROLE_PMT_HOME_AUTH_RENEW_ENTRY = 39004;
    int TM_ROLE_PMT_HOME_AUTH_RENEW_VERIFICATION = 39005;
    int TM_ROLE_PMT_HOME_AUTH_RENEW_APPROVAL = 39006;
    int TM_ROLE_PMT_HOME_AUTH_RENEW_PRINT = 39007;
    int TM_ROLE_PMT_SURRENDER_ENTRY = 41004;
    int TM_ROLE_PMT_SURRENDER_REVERT = 35804;
    int TM_ROLE_PMT_SURRENDER_VERIFICATION = 41005;
    int TM_ROLE_PMT_SURRENDER_APPROVAL = 41006;
    int TM_ROLE_PMT_RESTORE_ENTRY = 42004;
    int TM_ROLE_PMT_RESTORE_VERIFICATION = 42005;
    int TM_ROLE_PMT_RESTORE_APPROVAL = 42006;
    int TM_ROLE_PMT_REPLACE_VEH_ENTRY = 43004;
    int TM_ROLE_PMT_REPLACE_VEH_VERIFICATION = 43005;
    int TM_ROLE_PMT_REPLACE_VEH_APPROVAL = 43006;
    int TM_ROLE_PMT_TO_REPLACE_VERIFICATION = 45005;
    int TM_ROLE_PMT_TO_REPLACE_OTHER_OFFICE_VERIFICATION = 40505;
    int TM_ROLE_PMT_TO_REPLACE_APPROVAL = 45006;
    int TM_ROLE_PMT_TO_REPLACE_OTHER_OFFICE_APPROVAL = 40506;
    int TM_ROLE_PMT_PERMANENT_SURRENDER_VERIFICATION = 46005;
    int TM_ROLE_PMT_PERMANENT_SURRENDER_APPROVAL = 46006;
    int TM_ROLE_EXEMPTION_APPL_ENTRY = 88876;
    int TM_ROLE_PMT_EXEMPTION_VERIFICATION = 47005;
    int TM_ROLE_PARK_EXEMPTION_VERIFICATION = 35305;
    int TM_ROLE_FITNESS_EXEMPTION_VERIFICATION = 35105;
    int TM_ROLE_PMT_RE_ASSIGMENT_VERIFICATION = 49005;
    int TM_ROLE_PMT_EXEMPTION_APPROVAL = 47006;
    int TM_ROLE_PARK_EXEMPTION_APPROVAL = 35306;
    int TM_ROLE_FITNESS_EXEMPTION_APPROVAL = 35106;
    int TM_ROLE_PMT_RE_ASSIGMENT_APPROVAL = 49006;
    int TM_ACTION_REGISTERED_VEH_FEE = 99992;
    int TM_ROLE_PMT_FEE = 99989;
    int TM_ROLE_NEW_REGISTRATION_FEE = 99991;
    int TM_ROLE_NEW_REGISTRATION_FIT_FEE = 99901;
    int TM_ROLE_DEALER_NEW_REGISTRATION_FIT_FEE = 12311;
    int TM_ROLE_TEMP_REGISTRATION_FEE = 99993;
    int TM_ROLE_TAX_COLLECTION = 99994;
    int TM_PAYTMENT_CASH = 4;
    int TM_ROLE_FANCY_ADVANCE_REGN_FEE = 99997;
    int TM_ROLE_PMT_TEMP_APPL = 88887;
    int TM_ROLE_PMT_SPECIAL_APPL = 88879;
    int TM_ROLE_PMT_TEMP_VERIFICATION = 35005;
    int TM_ROLE_PMT_RENEW_TEMP_VERIFICATION = 53005;
    int TM_ROLE_PMT_TEMP_APPROVAL = 35006;
    int TM_ROLE_PMT_RENEW_TEMP_APPROVAL = 53006;
    int TM_ROLE_PMT_SPECIAL_VERIFICATION = 36005;
    int TM_ROLE_PMT_SPECIAL_APPROVAL = 36006;
    int TM_ROLE_PMT_APPLICATION_ENTRY = 25004;
    int TM_ROLE_PMT_APPLICATION_VERIFICATION = 25005;
    int TM_ROLE_PMT_APPLICATION_APPROVAL = 25006;
    int TM_ROLE_PMT_DUPL_APPLICATION = 88878;
    int TM_ROLE_PMT_DUPL_VERIFICATION = 34005;
    int TM_ROLE_PMT_DUPL_APPROVAL = 34006;
    int TM_PMT_APPL_PRINT = 25007;
    int TM_PMT_FRESH_PRINT = 26007;
    int TM_PMT_RENEWAL_PRINT = 27007;
    int TM_PMT_DUPLICATE_PRINT = 34007;
    int TM_PMT_TEMP_PRINT = 35007;
    int TM_PMT_RENEW_TEMP_PRINT = 53007;
    int TM_PMT_SPECIAL_PRINT = 36007;
    int TM_PMT_COUNTER_SIGNATURE_PRINT = 38007;
    int TM_PMT_LEASE_PERMIT_PRINT = 40107;
    int TM_PMT_VARIATION_ENDORSEMENT_PRINT = 31007;
    int TM_PMT_REPLACE_VEHICAL_PRINT = 43007;
    int TM_PMT_TO_REPLACE_OTHER_STATE_PRINT = 40507;
    int TM_PMT_TO_REPLACE_PRINT = 45007;
    String TM_FEE_REG_TYPE = "RF";
    String TM_FEE_TAX_TYPE = "TX";
    String TM_FEE_PERMIT_TYPE = "PF";
    String TM_FEE_TRADE_TYPE = "TF";
    String TM_FEE_SERVICE_CHARGE_TYPE = "SF";
    String PAYMENT_INWARD_CONSTANT = "IB";
    String PAYMENT_MODE = "I";
    String HSRP_DUP_BOTH_SIDE = "DB";
    String HSRP_DUP_FRONT = "DF";
    String HSRP_DUP_REAR = "DR";
    String HSRP_NEW_BOTH_SIDE = "NB";
    String HSRP_OLD_BOTH_SIDE = "OB";
    String USER_CATG_PORTAL_ADMIN = "P";
    String USER_CATG_STATE_ADMIN = "S";
    String USER_CATG_STATE_SUPER_ADMIN = "C";
    String USER_CATG_OFFICE_ADMIN = "A";
    String USER_CATG_FITNESS_CENTER_ADMIN = "F";
    String USER_CATG_FITNESS_CENTER_USER = "E";
    String USER_CATG_OFF_STAFF = "L";
    String USER_CATG_DEALER = "B";
    String USER_CATG_DEALER_ADMIN = "D";
    String USER_CATG_SMARTCARD = "X";
    String USER_CATG_HSRP = "Y";
    String USER_CATG_STATE_HSRP = "W";
    String USER_CATG_STATE_SMARTCARD = "V";
    String USER_CATG_REPORT_ADMIN = "R";
    int TM_ROLE_CREATE_USER = -5;
    int HSRP_VENDOR_FLAT_FILE = 77772;
    int HSRP_VENDOR_UPLOAD_FILE = 77776;
    int TM_ROLE_ASSIGN_ROLE = -6;
    int TM_ROLE_CONV_ENTRY = 11004;
    int TM_ROLE_CONV_VERIFICATION = 11005;
    int TM_ROLE_CONV_APPROVAL = 11006;
    int PRINT_REPORT = -2;
    String PRINT_FORM20_21_CURRENT_RECEIPT = "/ui/dealer/form_printDealerReports.xhtml?faces-redirect=true";
    String VAHAN_PGI_KEY = "VAHANPGI";
    String VAHAN_NEWREGISTRATION_KEY = "NEWREGISTRATION";
    String VAHAN_PGI_CONNTYPE = "VAHANPGI";
    String VAHAN_PGI_CHECK_FAIL_CONNTYPE = "VAHANPGI_VER";
    String VAHAN_PGI_EGRASS_CHECK_FAIL_CONNTYPE = "VAHANPGI_EGRASS";
    String DEALER_PAYMENT_REVERIFICATION = "R";
    String DEALER_PAYMENT_VERIFICATION = "N";
    String REVERIFY_WALLET = "W";
    String REVERIFY_REVERT = "R";
    String NO_GEN_TYPE_SEQ = "S";
    String NO_GEN_TYPE_RAND = "R";
    String NO_GEN_TYPE_MIX = "M";
    String NO_GEN_TYPE_MIX_P = "P";
    String VAHAN_PGI_SUCCESS = "S";
    String VAHAN_PGI_FAIL = "F";
    String VAHAN_PGI_PENDING = "P";
    String INS_TYPE_NA = "4";
    int VEH_TYPE_GOVT = 4;
    int VEH_TYPE_STATE_GOVT = 5;
    int VEH_TYPE_GOVT_UNDERTAKING = 6;
    int VEH_TYPE_POLICE_DEPT = 15;
    int VEH_TYPE_STATE_TRANS_DEPT = 16;
    int VEH_TYPE_LOCAL_AUTHORITY = 11;
    int RCPT_UPPER_BOUND = 999999999;
    int RCPT_LOWER_BOUND = 1;
    String VAHAN_PGI_MERCHANT_CODE = "VAHAN4";
    String PAY_GATE = "EGRAS";
    String SERVICE_CHARGE_PER_RCPT = "R";
    String SERVICE_CHARGE_PER_TRANS = "T";
    String THEFT = "Theft";
    String DESTROYED = "Destroyed";
    int BLDestroyedAccidentCode = 10;
    int BLTheftCode = 1;
    int BLScrappedCode = 7;
    int BLLoanDefaulterCode = 11;
    int BLConfiscationCode = 12;
    int BLCompoundingAmtCode = 62;
    String PURCHASE_AS_CHASIS = "C";
    int TAX_CLEAR_PUR_CD = 345;
    int TAX_INSTALLMENT_PUR_CD = 355;
    String ALL_INDIA = "AI";
    int ALL_INDIA_OFF_CD = 0;
    String SERIES_EXHAUST_MESSAGE = "Either Vehicle Series has been Exhausted or Vehicle Series has not been entered!!! Please contact administrator!!!";
    String TWO_WHEELER_NON_TRANSPORT = "2WN";
    String TWO_WHEELER_TRANSPORT = "2WT";
    String CASHIER = "CASH";
    String FitnessResultPass = "Y";
    String FitnessResultFail = "N";
    int SWAPPING_REGN_PUR_CD = 10;
    int SWAPPING_REGN_FEE = 99992;
    int SWAPPING_REGN_VERIFICATION = 10115;
    int SWAPPING_REGN_APPROVAL = 10116;
    String TAX_MODE_YEARLY = "Y";
    String TAX_MODE_HALF_YEARLY = "H";
    String TAX_MODE_QUARTER = "Q";
    String TAX_MODE_MONTHLY = "M";
    String TAX_MODE_LIFE_TIME = "L";
    String TAX_MODE_ONE_TIME = "O";
    String TAX_MODE_LUMP_SUM = "S";
    String TAX_MODE_BALANCE = "B";
    String TO_SUCCESSION = "Succession";
    String TO_THEFT = "Theft";
    String PaymentMode_MIX = "Mixed";
    String ONLINE_APPL_STATUS_PAYMENT_SUCCESSFUL = "S";
    String ONLINE_APPL_STATUS_PAYMENT_REQUEST = "R";
    String MOVED_FROM_ONLINE_APPL_STATUS_YES = "Y";
    String MOVED_FROM_ONLINE_APPL_STATUS_NO = "N";
    int TM_ROLE_TAX_EXEMPT_ENTRY = 12504;
    int TM_ROLE_TAX_EXEMPT_VERIFICATION = 12505;
    int TM_ROLE_TAX_EXEMPT_APPROVAL = 12506;
    int TM_ROLE_TAX_EXEMPT_CANCEL_ENTRY = 44504;
    int TM_ROLE_TAX_EXEMPT_CANCEL_VERIFICATION = 44505;
    int TM_ROLE_TAX_EXEMPT_CANCEL_APPROVAL = 44506;
    int TAX_EXAMPT_PUR_CD = 125;
    int TAX_EXAMPT_CANCEL_PUR_CD = 445;
    int TM_ROLE_PRINT_TAXCC = 34507;
    String RENEWAL_VALID_FROM_FOR_APPROVAL_DATE_FLAG = "A";
    String RENEWAL_VALID_FROM_FOR_FEE_SUBMITTED_DATE_FLAG = "F";
    String RENEWAL_VALID_FROM_FOR_PRIVIOUS_PERMIT_VALID_UPTO_DATE_FLAG = "P";
    int DUPLICATE_HSRP_PUR_CD = 126;
    int DUPLICATE_HSRP_ENTRY_CD = 12604;
    int DUPLICATE_HSRP_APPROVAL_CD = 12606;
    int DUPLICATE_HSRP_PUR_CD_VENDOR = 136;
    int DUPLICATE_HSRP_ENTRY_CD_VENDOR = 13604;
    int DUPLICATE_HSRP_APPROVAL_CD_VENDOR = 13606;
    int TM_ROLE_SKIP_FEE = 90000;
    String TRADE_CERT_EXPIRED = "Trade Certificate has been expired. Last Validity was ";
    String DEALER_VALIDITY_EXPIRED = "Dealer Validity has been expired. Last Validity was ";
    String DEALER_EXPIRED = "Dealer Validity has been expired/Trade Certificate has been expired !!!";
    int VM_TRANSACTION_MAST_GREEN_TAX = 69;
    String HOMOLOGATION_DATA = "HOMO-DATA";
    String NotApplicableValue = "NA";
    String permitOfferLetterActive = "A";
    int CANCEL_CASH_RCPT_ADMIN = 99913;
    int CANCEL_CASH_RCPT = 99911;
    String DEALER_RCPT_FLAG = "D";
    String DEALER_PAYMENTID_FLAG = "T";
    String CASH_RCPT_FLAG = "R";
    String MODE_YEARLY = "Y";
    String MODE_HALF_YEARLY = "H";
    String MODE_QUARTER = "Q";
    String MODE_MONTHLY = "M";
    String NOC_ENDORSEMENT = "Please Do the NOC Endorsement of this Vehicle/Chassis No.!!!";
    String NOC_DATA_NOT_FOUND = "NOC is not Available for this Registration!!!";
    String NOC_DATA_NOT_FOUND_CHASSIS = "Data not found for this Chassis No!!!";
    String NOC_MONTH_ERROR = "NOC Issue Date should be more than one month from current date!!!.";
    String NOC_DAY_ERROR = "Vehicle cannot be VERIFY on the same day of NOC issue date !!!.";
    String INVALID_FOR_NOC_ENDORSEMENT = "Not Valid For NOC Endorsement!!!";
    int VM_MAST_TEMP_RC_CANCEL = 357;
    int VM_ROLE_TEMP_RC_CANCEL_ENTRY = 35704;
    int VM_ROLE_TEMP_RC_CANCEL_VERIFY = 35705;
    int VM_ROLE_TEMP_RC_CANCEL_APPROVE = 35706;
    String EGRASS_BANK_CODE = "EGRS";
    String EGRASS_BANK_DESCR = "E-GRASS";
    String EGRASS_INSTRUMENT_CODE = "G";
    String ANY_OTHER_BANK_CODE = "9999";
    String MANUAL_RCPT_INSTRUMENT_CODE = "M";
    String MPOS_INSTRUMENT_CODE = "P";
    String MPOS_BANK_CODE = "MPOS";
    String MPOS_BANK_DESCR = "POS MACHINE";
    String INSTRUMENT_CODE_CHEQUE = "C";
    String INSTRUMENT_CODE_BANK_CHALLAN = "L";
    String INSTRUMENT_CODE_BANK_RECEIPT = "R";
    String INSTRUMENT_TRANSFER = "T";
    String NOC_VERIFICATION = "Please Do the NOC Verification of this Vehicle/Chassis No.!!!";
    String INVALID_FOR_NOC_VERIFICATION = "Not Valid For NOC Verification!!!";
    String CARRIERCATEGORY = "CARRIER";
    int CARRIERSECURITYFEE = 359;
    int VM_TRANSACTION_CARRIER_REGN = 360;
    int VM_TRANSACTION_CARRIER_RENEWAL = 361;
    int VM_TRANSACTION_CARRIER_AMENDMENT = 362;
    int VM_TRANSACTION_PVT_VEH_IMPOUND_CF_OTHER_STATE = 364;
    int VM_TRANSACTION_PVT_VEH_IMPOUND_CF_HOME_STATE = 363;
    int VM_APPEAL_CARRIER_REGN = 371;
    int VM_PROCESSING_CARRIER_REGN = 372;
    String ULD_WT_ERR_MESS = "UnLaden Weight should be greater than or equal to Homologation UnLaden Weight!!!";
    String SALE_AMT_ERR_MESS = "Sale Amount should be greater than or equal to Homologation Sale Amount!!!";
    String SEAT_CAP_ERR_MESS = "Seat Cap should be greater than or equal to Homologation Seat Cap!!!";
    String SomthingWentWrong = "Something Went Wrong, Please Contact to the System Administrator.";
    String VEH_CATG_ERR_MESS = "Please do Temporary registration of transport vehcile as New Registration is not allowed.!!!";
    int FITNESS_APPROVAL = 20006;
    String TRAILER_VEH_CLASS = ",90,89,28,30,";
    String TRACTOR_VEH_CLASS = ",13,63,84,";
    String RTO_PAYMENTID_FLAG = "M";
    String VM_TRANS_MAST_NEW_VEHICLE_SMART_CARD = "NEW";
    //List of Actions for entry case which is allowed to inward for registered vehicle//
    int ALTERATION_OF_MOTOR_VEHICLE_ENTRY = 16004;
    int CANCELLATION_OF_RC_BY_AUTHORITY_ENTRY = 61004;
    int CANCEL_NOC_BY_OWNER_ENTRY = 91004;
    int CHANGE_OF_ADDRESS_IN_RC_ENTRY = 40004;
    int INSPECTION_FOR_CHANGE_OF_ADDRESS = 40003;
    int CHANGE_OF_ADDRESS_IN_RC_APPROVAL = 40006;
    int CONVERSION_OF_VEHICLE_ENTRY = 11004;
    int DUPLICATE_FC_ENTRY = 14004;
    int FITNESS_CANCELLATION_ENTRY = 35204;
    int FITNESS_INSPECTION_CERTIFICATE_ENTRY = 20004;
    int FITNESS_INSPECTION_CERTIFICATE_VERIFICATION = 20005;
    int FITNESS_INSPECTION_APP = 20009;
    int FRESH_RC_TO_FINANCIER_ENTRY = 12004;
    int HYPOTHECATION_ADDITION_ENTRY = 60004;
    int HYPOTHECATION_TERMINATION_ENTRY = 70004;
    int ISSUE_OF_DUPLICATE_RC_ENTRY = 30004;
    int ISSUE_OF_NOC_ENTRY = 90004;
    int ISSUE_OF_NOC_VERIFY = 90005;
    int ISSUE_OF_NOC_APPROVE = 90006;
    int ISSUE_OF_NDC_ENTRY = 17504;
    int ISSUE_OF_NDC_VERIFY = 17505;
    int ISSUE_OF_NDC_APPROVE = 17506;
    int RC_PARTICULARS_AGAINST_FEE_ENTRY = 13004;
    int RC_PARTICULARS_FOR_OFFICE_PURPOSE_WITHOUT_FEE_ENTRY = 73004;
    int RC_RELEASE_ENTRY = 66004;
    int RC_SURRENDER_ENTRY = 65004;
    int RE_ASSIGNMENT_OF_REGISTRATION_NO_ENTRY = 17004;
    int RENEWAL_OF_REGISTRATION_ENTRY = 15004;
    int SCRAPPED_VEHICLE_ENTRY = 34904;
    int TRANSFER_OF_OWNERSHIP_ENTRY = 50004;
    int TM_ROLE_PRINT_FC = 20007;
    int TM_ROLE_PRINT_PRINTED_RC = 10017;
    int TM_ROLE_REPRINT_FC = 20117;
    int TM_ROLE_DEALER_PRINT_RC = 12314;
    //array of entry action code for checking insurance validity 
    int[] INSURANCE_VALIDITY_CHECK_ACTIONS = {
        ALTERATION_OF_MOTOR_VEHICLE_ENTRY,
        CHANGE_OF_ADDRESS_IN_RC_ENTRY,
        CONVERSION_OF_VEHICLE_ENTRY,
        DUPLICATE_FC_ENTRY,
        FITNESS_CANCELLATION_ENTRY,
        FITNESS_INSPECTION_CERTIFICATE_ENTRY,
        HYPOTHECATION_ADDITION_ENTRY,
        HYPOTHECATION_TERMINATION_ENTRY,
        ISSUE_OF_DUPLICATE_RC_ENTRY,
        ISSUE_OF_NOC_ENTRY,
        RENEWAL_OF_REGISTRATION_ENTRY,
        TRANSFER_OF_OWNERSHIP_ENTRY};
    int PollutionFee = 159;
    String HOMOLOGATION_CHASI_NO_MESS = "Chassis No exist in Homologation data. !!!";
    String DETACH_LINKED_TRAILER = "L";
    String DETACH_TRAILER = "N";
    String ONLINE_PAYMENT = "9999999999";
    int TAX_ASSESMENT = 99111;
    int TECHNICAL_DATA_VERIFICATION = 365;
    int TECHNICAL_DATA_VERIFICATION_APPROVAL = 36506;
    int FEE_FINE_EXEMTION = 251;
    int TAX_PENALTY_EXEMTION = 252;
    String FEE_FINE_EXEMTION_HEAD = "Fee Fine Exemption";
    String TAX_PENALTY_EXEMTION_HEAD = "Tax Penalty Exemption";
    int RANDOM_ODD_EVEN_FEE = 87;
    int RE_POSTAL_PUR_CD = 201;
    int VM_MAST_NON_USE = 366;
    int VM_MAST_NON_USE_RESTORE_REMOVE = 367;
    int VM_ROLE_NON_USE_INTIMATION_ENTRY = 36604;
    int VM_ROLE_NON_USE_INTIMATION_VERIFY = 36605;
    int VM_ROLE_NON_USE_INTIMATION_APPROVE = 36606;
    int VM_ROLE_NON_USE_RESTORE_REMOVE_ENTRY = 36704;
    int VM_ROLE_NON_USE_RESTORE_REMOVE_VERIFICATION = 36705;
    int VM_ROLE_NON_USE_RESTORE_REMOVE_APPROVAL = 36706;
    String VM_PAPER_RC_CD = "23";
    String VM_PLASTIC_CARD_RC_CD = "23A";
    String VM_PLASTIC_CARD_RC_PVC_CD = "23P";
    int TM_ROLE_REPRINT_TMP_RC = 18017;
    String TAX_INTEREST_EXEMTION_HEAD = "Tax Interest Exemption";
    int TAX_INTEREST_EXEMTION = 253;
    int POSTAL_PUR_CD = 200;
    int POSTAL_FEE_MASTERS = 15;
    int POSTAL_FEE = 35;
    String CONV_ACTION = "CON";
    String LIGHT_GOODS_VEH = "LGV";
    String MEDIUM_GOODS_VEH = "MGV";
    String HEAVY_GOODS_VEH = "HGV";
    String PRIVATE_SERVICE_VEHICLE = "69";
    int OWNER_CATG_PHYSICALLY_HANDICAPPED = 2;
    String INVALID_CARRIAGE = "5";
    String GCW_VEH_CLASS = ",13,63,90,84,";
    String SPEEDGOV_OTHERS = "99";
    int VM_FEE_PAYMENT_AUDIT = 232;
    String NEW_APPL_SAVETYPE_PARTIAL = "partial";
    String NEW_APPL_SAVETYPE_COMPLETE = "complete";
    String EMPTY_STRING = "";
    int EMPTY_INT = 0;
    String PURCHASE_AS_FULLY_BODYBUILT = "B";
    String REN_FROM_CURRNT_DT = "CUR_DT";
    String REN_FROM_FIT_UPTO = "FIT_UPTO";
    String PROJECT_NAME = "V4";
    String STOCK_TRANSFER = "OM";
    String FITNESS_PURPOSE_DESCR = "Fitness Inspection+Certificate";
    String DUPLICATE_FC_DESCR = "Duplicate FC";
    String RC_PARTICULARS_AGAINST_FEE = "RC Particulars against Fee";
    String TRANSFER_OF_OWNERSHIP = "Transfer of Ownership";
    String FITNESS_CANCELLATION = "Fitness Cancellation";
    String RENEWAL_OF_REGISTRATION_PURPOSE_DESCR = "Renewal of Registration";
    String FITNESS_INSPECTION_PURPOSE_DESCR = "Fitness Inspection";
    String SCRAP_THEFT_CASE = "Stolen Vehicle, Untraced Report of Police Deptt, Scrapped when Recovered";
    String LOGIN_TYPE_OTP = "O";
    String LOGIN_TYPE_PASSWORD = "P";
    String MORNING_TIMING_OTP = "08:00:00-19:59:59";
    String EVENING_TIMING_OTP = "20:00:00-07:59:59";
    String SECURITY_KEY = "&j_key=vVl%2FAz1yGsjOAG18WDeScg%3D%3D&j_securityKey=6D6C069D681B40DBF95CAD7B3ED71BE1A46F0A7036BC711860B00BAAE50FE8A4%21TZFIMZbTiUtqXMfARJ1DGgyNicWFwYkwTA0ip%2FQ8Wns%3D";
    String DMS_CON_VER = "DMS_CON_VER";
    String DOCUMENT_VIEW_STATUS = "P";
    String DOCUMENT_MODIFY_STATUS = "NP";
    String DOCUMENT_RTO_VERIFICATION = "RTV";
    String DOCUMENT_RTO_APPROVAL = "RTA";
    String DOCUMENT_TEMP_APPROVAL = "RTTV";
    String DOCUMENTS_NOT_UPLOAD_ERR_MESSG = "Documents has not been uploaded/modified for the Application No. ";
    String DOCUMENTS_UPLOAD_SUCCESS = "Documents has been successfully uploaded/modified/viewed for the Application No. ";
    String DOCUMENTS_VERIFY_SUCCESS = "Documents has been successfully verified for the Application No. ";
    String DOCUMENTS_NOT_VERIFY_MESSG = "Below Documents has not been verified. Try again for the Application No. ";
    String DOCUMENTS_APPROVE_SUCCESS = "Documents has been successfully approved for the Application No ";
    String DOCUMENTS_NOT_APPROVE_MESSG = "Below Documents has not been approved. Try again for the Application No. ";
    String DMS_CON = "DMS_CON";
    String DMS_SERVICE_URL = "dms_url_ser_tc";
    String DMS_USRMSG_URL = "DMS_USRMSG";
    int AGENT_DETAIL_APPLICATION = 99814;
    int AGENT_DETAIL_FEE = 99811;
    int AGENT_DETAIL_VERIFICATION = 99815;
    int AGENT_DETAIL_APPROVAL = 99816;
    int AGENT_DETAIL_PRINT = 99817;
    int AGENT_DETAIL_PUR_CD = 375;
    int AGENT_DETAIL_REN_PUR_CD = 376;
    int AGENT_DETAIL_DUP_PUR_CD = 377;
    String KL_TAX_URL = "KL_TAX_URL";
    String KL_TAXRATE_URL = "KL_TAXRATE_URL";
    String KL_ENDORTAX_URL = "KL_ENDORTAX_URL";
    String VHC_TRANSPORT_CATG = "51,53,55,69,75,76,77,78,73,57,56,70,71,86";
    String VH_CLASS_ALLOWED_ZERO_SEAT_CAP = "28,30,82,89,90";
    String OTHER_OFFICE_ROUTE_ALLOWED_FOR_PERMIT = "1,2,5,7,9,14,19,20,22,23,27,29";
    int VM_ROLE_REVERT_GENERATED_RC_TO_OFF_STAFF = 77783;
    int VM_ROLE_REVERT_GENERATED_RC_TO_OFF_ADMIN = 20019;
    int VM_TRANSACTION_MAST_FIT_REVOKE = 354;
    int FITNESS_REVOKE_ENTRY = 35404;
    int FITNESS_REVOKE_VERIFICATION = 35405;
    int FITNESS_REVOKE_APPROVAL = 35406;
    int ERICKSHAW_VCH_CLASS = 55;
    String DRIVING_LICENSE_URL = "DL_CON_URL";
    String LEARNING_LICENSE_URL = "LL_CON_URL";
    String SUBSIDY_PENDING_STATUS = "P";
    String SUBSIDY_VERIFIED_STATUS = "V";
    String SUBSIDY_RECOMMENDED_STATUS = "R";
    String SUBSIDY_RECORDS_PRINT_STATUS = "U";
    String SUBSIDY_GRANTED_STATUS = "S";
    int VM_SUBSIDY_VERIFY = 10020;
    int VM_SUBSIDY_RECOMMENDED = 10018;
    int VM_SUBSIDY_RECORD_PRINT_GRANT = 10019;
    int ADMIN_OWNER_DATA_CHANGE = 101;
    int TM_ADMIN_OWNER_DATA_CHANGE_APPROVAL = 10106;
    int TM_ADMIN_OWNER_DATA_CHANGE_VERIFY = 10105;
    int TM_ADMIN_OWNER_DATA_CHANGE_ENTRY = 10104;
    String VALIDATE_SEAT_CAP_ZERO = ",M3,T4,";
    String VALIDATE_LADEN_UNLDEN_WT = ",A,C,N3,";
    String VALIDATE_LADEN_WT = ",A,C,M3,T4,";
    String VALIDATE_UNLDEN_WT = ",M3,";
    int VM_FUEL_TYPE_OTHERS = 99;
    String OFFICE_TIMING_EXEMPTION_CATG = ",S,A,C,D,X,Y,B,F,Z,W,V,";
    String ERICK_HOMO_VCH_CLASS = ",ERICK,ECART,T1,T2,T3,T4,T5,";
    String RC_SURRENDER = "RCSun";
    String RC_CANCEL = "RCCn";
    String RC_SUSPENSION = "RCSus";
    int VM_COMMON_CARRIER_REGISTRATION = 99912;
    int VM_COMMON_CARRIER_APPL_ENTRY = 99954;
    int VM_COMMON_CARRIER_APPL_VERIFY = 99955;
    int VM_COMMON_CARRIER_APPL_APPROVE = 99956;
    int VM_TRANSACTION_CARRIER_DUPLICATE = 378;
    String RC_INWARD_SURRENDER = "rcSur";
    String RC_INWARD_SUSPENSION = "rcSus";
    int VM_TRANSACTION_MAST_RC_TO_SMART_CARD_CONVERSION = 88;
    int VM_ROLE_REGISTRATION_NO_ASSIGNMENT_RTO = 89004;
    int VM_ROLE_REGISTRATION_NO_ASSIGNMENT_DEALER = 89017;
    String INSTRUMENT_NEFT_RTGS = "N";
    int TM_ROLE_DEALER_DOCUMENT_MODIFY = 12313;
    String REJECTED_DOCUMENT_MODIFY_STATUS = "RTNV";
    int SPECIAL_TAX = 97;
    int COURT_PUR_FEE = 74;
    int STAMP_FEE = 198;
    int DELETE_SMART_CARD_FLAT_FILE = 381;
    int DELETE_SMART_CARD_FLAT_FILE_ENTRY = 38104;
    int DELETE_SMART_CARD_FLAT_FILE_APPROVE = 38106;
    int TM_ROLE_REASIGN_APPROVAL = 17006;
    int RC_CANCEL_BY_AUTHORITY = 0;
    int VM_PMT_TEMP_SUR_PUR_CD = 404;
    String NORMS_NOT_ALLOWED = ",1,2,3,7,8,9,";
    int RETENTION_OF_REGISTRATION_NO_PUR_CD = 331;
    int RETENTION_ENTRY = 33104;
    int RETENTION_VERIFICATION = 33105;
    int RETENTION_APPROVAL = 33106;
    String VH_CLASS_ALLOWED_SPL_PMT_OR = ",70,71,86,56,75,69,73,";
    String ONLINE_TAX = "T";
    String ONLINE_FANCY = "F";
    String ONLINE_AUDIT = "U";
    String OMVT_NON_PAYMENT_OF_TAX_UNDER_OMVT = "29";
    String CARRYING_OVERLOAD = "194";
    int VM_TRANSACTION_MAST_SHOWROOM_INSPECTION_FEE = 84;
    String ALL_INDIA_DEALER_CD = "AI99999999";
    int TM_ROLE_BLACK_LIST_VEHICLE = 83001;
    int TM_ROLE_RELEASE_BLACK_LIST_VEHICLE = 83002;
    int VM_CHANGE_OF_ADDRESS_PUR_CD = 4;
    int VM_TRANSFER_OWNER_PUR_CD = 5;
    int GOODS_CARRIER_VCH_CLASS = 59;
    String RESTOREDISPOSE = "R";
    int VM_TRANSACTION_MAST_PLASTIC_CARD = 79;
    int UPDATE_MISSING_PERMIT_ENTRY = 12904;
    int UPDATE_MISSING_PERMIT_VERIFY = 12905;
    int UPDATE_MISSING_PERMIT_APPROVAL = 12906;
    int MISSING_PERMIT_INFO_PUR_CD = 129;
    int PRINT_FEE = 167;
    //Endorsment Tax
    int ENDORSMENT_TAX = 119;
    int TM_ENDORSMENT_TAX_APPROVAL = 11906;
    int TM_ENDORSMENT_TAX_VERIFY = 11905;
    int TM_ENDORSMENT_TAX_ENTRY = 11904;
    //Dispose Endorsment Tax
    int DISPOSE_ENDRSMNT_TAX = 888;
    int DISPOSE_TM_ENDRSMNT_TAX_APPROVAL = 88806;
    int DISPOSE_TM_ENDRSMNT_TAX_VERIFY = 88805;
    int DISPOSE_TM_ENDRSMNT_TAX_ENTRY = 88804;
    String INSTRUMENT_O_GRASS = "O";
    int INSPECTION_FOR_ALT = 16003;
    String DMS_SARTHI_URL = "DMS_SARTHI";
    int TM_CESS_TAX = 60;
    int TM_ROLE_UPLOAD_MODIFY_DOCUMENT = 88810;
    int TM_ROLE_DEALER_DOCUMENT_UPLOAD = 12315;
    int TM_ROLE_PRINT_OWNER_DISCLAIMER = 10008;
    int VM_DISPOSE_APPLICATION = 88886;
    int VM_MAST_MANUAL_RECEIPT = 603;
    int VM_ROLE_MANUAL_RECEIPT_ENTRY = 60304;
    int VM_ROLE_MANUAL_RECEIPT_VERIFICATION = 60305;
    int VM_ROLE_MANUAL_RECEIPT_APPROVAL = 60306;
    String VH_MOVED_STATUS_DELETE = "D";
    String VH_MOVED_STATUS_UPDATE = "U";
    int CHECK_MANU_MONTH_YEAR_FOR_HSRP = 201904;
    String DMS_ESERVICE_PURPOSE_CD = "3,4,5,6,7,8,27,34,39,16,9";
    String DMS_URL = "DMS_URL";
    String FITNESS_RENEWAL_FOR_NOC_OR_CONVERSION = "FITNESS RENEWAL FOR NOC/CONVERSION (ONE MONTH PARKING CHARGES)";
    String FITNES_RENEWAL_NORMAL_CASE = "FITNESS RENEWAL (NORMAL CASE)";
    int OTHER_CRITERIA_MINE_VEH = 2;
    int STA = 99;
    String TRADE_CERT_APPLICANT_TYPE_CODE_DEALER = "D";
    String TRADE_CERT_APPLICANT_TYPE_CODE_MANUFACTURER = "M";
    String TRADE_CERT_APPLICANT_TYPE_CODE_FINANCIER = "F";
    String TRADE_CERT_APPLICANT_TYPE_CODE_RETRO_FITTER = "RF";
    String TRADE_CERT_APPLICANT_TYPE_CODE_SPEED_GOVERNOR = "SG";
    String TRADE_CERT_APPLICANT_TYPE_CODE_FARE_METER_REPAIRER = "FMR";
    String TRADE_CERT_APPLICANT_TYPE_CODE_BODYBUILDER = "BB";
    String TC_NO_GENERATION_ERROR_FOR_NEW_RTO = "Please contact System Administrator to initialize Trade-Certificate in selected RTO.";
    int PAPER_DOCUMENT_CHARGE = 452;
    int PERMIT_PAPER_DOCUMENT_CHARGE = 454;
    String VT_AUCTION_STATUS = "M";
    int VM_TRANSACTION_MAST_AUCTION = 106;
    int TM_ROLE_AUCTION_ENTRY = 10604;
    int TM_ROLE_AUCTION_VERIFICATION = 10605;
    int TM_ROLE_AUCTION_APPROVAL = 10606;
    int TM_OFFICE_CODE_FOR_STA = 9;
    String AUCTION_REMARK = "AUCTION/CONFISCATED VEH";
    String VAHAN_PGI_SBS_CHECK_FAIL_CONNTYPE = "VAHANPGI_SBS";
    String PAY_GATE_SBS = "SBS";
    String SBS_BANK_CODE = "2260";
    int ADVERTISEMENT_ON_VEHICLE_ENTRY = 46104;
    int ADVERTISEMENT_ON_VEHICLE_VERIFICATION = 46105;
    int ADVERTISEMENT_ON_VEHICLE_APPROVAL = 46106;
    String CS_AUTH_DOCUMENT = "16";
    String ALLOW_VH_CHASS_WITH_HOMO_MAKER = "28";
    int TM_STATEADMIN_OWNER_DATA_CHANGE_APPROVAL = 10811;
    int TM_STATEADMIN_OWNER_DATA_CHANGE_VERIFY = 10805;
    int TM_STATEADMIN_OWNER_DATA_CHANGE_ENTRY = 10804;
    int STATEADMIN_OWNER_DATA_CHANGE = 108;
    int INS_TYPE_THIRD_PARTY = 2;
    int VM_TRANSACTION_MAST_ADVERTISEMENT_ON_VEHICLE = 461;
    String OTP_URL = "OTP_URL";
    String SMS_URL = "SMS_URL";
    String EMAIL_URL = "EMAIL_URL";
    String TAX_INSTALLMENT = "TI";
    String FASTAG_URL = "FASTAG_URL";
    int VM_TRANSACTION_NDC = 175;
    int FITNESS_CENTER_OFF_TYPE_CODE = 5;
    String DMS_J_KEY = "vVl%2FAz1yGsjOAG18WDeScg%3D%3D";
    String DMS_J_SECURITYKEY = "6D6C069D681B40DBF95CAD7B3ED71BE1A46F0A7036BC711860B00BAAE50FE8A4%21TZFIMZbTiUtqXMfARJ1DGgyNicWFwYkwTA0ip%2FQ8Wns%3D";
    String DMS_UPLOAD_URL = "DMS_UPLOAD_API";
    String DMS_GET_DOCLIST = "DMS_GETLIST_API";
    String DMS_VIEW_URL = "DMS_VIEW_API";
    String DMS_UPDATE_URL = "DMS_UPDATE_API";
    String CRL_SERVICE_URL = "DSC_CRL_API_URL";
    String DMS_STATUS_CODE = "V001";
    String DMS_STATUS_MESS = "Success.";
    String DMS_UPLOAD_ACTION_CD = "12315,88810,12313,10005,10006,18006,18005,12306,12406,10001,10011,10105,10106";
    String UPLOADING_PDF_FILE_PATH = "DSC_UPLOAD_PATH";
    String PDF_EXTENSION = "pdf,PDF";
    String IMAGE_EXTENSION = "gif,jpeg,jpg,png,GIF,JPEG,JPG,PNG";
    String MANDATORY_DOCUMENTS_NOT_UPLOAD_ERR_MESSG = "Mandatory Documents has not been uploaded for the Application No. ";
    String AUCTION_MODULE = "A";
    String INSURANCE_FROM_SERVICE_MESSAGE = "Note : The shown insurance details have been uploaded by Insurance Company to Vahan, if any discrepencies found, the Vehicle Owner have to contact respective Insurance Company for uploading the Latest Correct Insurance Details on Vahan.";
    String INSURANCE_FROM_VAHAN_MESSAGE = "Note : The shown Insurance details have been entered by Respective Registering Authority on the basis of paper documents.";
    String HP_eAuction_TO_Stop_Msg = "As per the HP State Transport Department vide letter no CT. 70-6/72-Proposal/2020-1085563 dated 06-Aug-2020 the Transfer of Ownership is STOPPED only for Registration Number taken in e-Auction except TO with Retention.";
    String TRADE_CERTIFICATE_PRINTED = "Trade Certificate Printed";
    int TM_ROLE_DEALER_ADMIN_DSC_REGISTRATION = 12318;
    int TM_ROLE_OFF_ADMIN_DSC_REGISTRATION = 18012;
    int TM_ROLE_OFF_ADMIN_DSC_VERIFICATION = 18112;
    String REASSIGNMENT_OF_REGISTRATION_PURPOSE_DESCR = "Re-assignment of Registration No (RMA)";
    String VM_TEMP_REASON_OTHER_STATE = "OS";
    String VM_TEMP_REASON_STOCK_TRANSFER = "OM";
    String VM_REGN_TYPE_CONFISCATED_AUCTION = "C";
    String TAX_MODE_FIVE_YEAR = "Y5";
    String TAX_MODE_TEN_YEAR = "Y10";
    String TAX_MODE_FIFTEEN_YEAR = "Y15";
    int TM_RTOADMIN_OWNER_DATA_CHANGE_APPROVAL = 10812;
}
